### ISSUE TITLE
Pull request not entirely merged

### ISSUE THREAD

**Issue by hyandell** [awslabs/aws-centralized-logging#6] opened 2018-11-12 23:36 UTC
If you look at https://github.com/awslabs/aws-centralized-logging/pull/3/files you can see that there is a .github/PULL_REQUEST_TEMPLATE.md file that didn't end up merged in.

**Comment by maykays** [comment] 2020-08-24 15:21
Duplicate of #20

**Closed by maykays** 2020-08-24 15:21 UTC
